site_name: GetAccept
nav:
  - "Documentation":
      - "Overview": "index.md"
      - "Requirements": "requirements.md"
      - "How it Works": "howitworks.md"
      - "Installation": "installation.md"
      - "Configuration": "configuration.md"
      - "Upgrading": "upgrading.md"
      - "Technical": "technical.md"
      - "Troubleshooting": "troubleshooting.md"
  - "Changelog":
      - "GetAccept add-on": "changelog.md"
repo_url: https://github.com/getaccept/addon-getaccept-lime
repo_name: "getaccept/addon-getaccept-lime"
site_description: GetAccept
site_author: GetAccept AB
docs_dir: docs
dev_addr: localhost:3002
theme:
  name: "material"
  logo:
    icon: "home"
  feature:
    tabs: true
  palette:
    primary: "teal"
    accent: "teal"
  favicon: "images/favicon.ico"
site_url: ""
markdown_extensions:
  - codehilite
  - admonition
  - meta
  - footnotes
